import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
// import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { fetcher } from '@/lib/fetcher';
import { usePostSWR } from '@/hooks/usePostSWR';
import Link from 'next/link';
import Navigation from '@/components/Navigation';

type Props = {
  fallbackData: TestApiResponseType[];
};

const Post: NextPage<Props> = ({ fallbackData }) => {
  /**
   * @description useSWR のカスタムフック
   * getStaticProps からの fallbackDataを初期値に持つ。
   * クライアント側でのデータフェッチを行う。
   */
  const { data } = usePostSWR(fallbackData);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Navigation />
        <ul>
          {data?.map((item) => (
            <li key={item.id}>
              <Link href={`/posts/${item.id}`}>{item.title}</Link>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const API_URL_ROOT = process.env.NEXT_PUBLIC_API_URL_ROOT;
  if (typeof API_URL_ROOT === 'undefined') {
    return {
      props: {
        fallbackData: undefined,
      },
    };
  }

  const data = await fetcher(API_URL_ROOT);
  return {
    props: {
      fallbackData: data,
    },
  };
};

export default Post;
